# Нужно указать редиректы, т.к. у нас 'Single Page Application'
# Иначе при обновлении страницы на сервере будет ошибка

[[redirects]]
  from = "/service-worker.js" # файл манифеста
  to = "/"                # никуда не переводим
  status = 200

[[redirects]]
  from = "/*"        # c любого маршрута
  to = "/index.html" # переводим на 'index.html', где подгрузится 'SPA', у которого свой механизм роутинга
  status = 200
