# Секреты задаются на GitHub: Settings => Security => Secrets and variables => Actions

# HOST = 103.13.210.44
# USERNAME = root
# PASSWORD = 1234567qwertyA

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Executing remote SSH commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

          # команды, чтобы избежать ошибки 'npm: command not found'
            # export NVM_DIR="$HOME/.nvm"
            # [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          script: |
            cd ~/ulbi_react

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            git pull

            ~/ulbi_react/.deploy/deploy.sh
