#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# husky позволяет запускать различные проверки/скрипты перед коммитом

# необходимо запускать storybook перед коммитом

# команду "npm run prepare" можно удалить из package.json после инициализации husky,
# т.к. заново инициализировать husky незачем

npm run build:prod
npm run lint:ts
npm run lint:scss
npm run test:unit
# npm run storybook:build
# npm run test:ui
