#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 'husky' позволяет запускать различные проверки/скрипты перед коммитом

# инициализация 'husky' для проекта: npx husky-init

# команду 'npm run prepare' можно удалить из 'package.json' после инициализации 'husky',
# т.к. заново инициализировать 'husky' незачем

# запуск проверок для всех файлов (измененных и неизмененных) перед коммитом:
# npm run build:prod
# npm run lint:ts
# npm run lint:scss
npm run test:unit
# npm run storybook:build
# npm run test:ui:ci

# 'lint-staged' запускает проверки только для измененных файлов, а не для всех,
# настройки 'lint-staged' в 'package.json'
npx lint-staged
