name: linting, testing, building

# запуск GitHub actions будет происходить на push и pull request (ветка 'master')
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pipeline: # любое название для job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ] # задаем версию для Node.js

    steps:
      - uses: actions/checkout@v2

      # устанавливаем в среду, где будут запускаться GitHub Actions, заданную выше версию Node.js
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Даем добро на установку peer-dependencies
      - name: Set legacy-peer-deps
        run: npm config set legacy-peer-deps true

      # устанавливаем node_modules
      - name: Install modules
        run: npm install

      # собираем production build
      - name: Build production project
        run: npm run build:prod

      # проверяем корректность TypeScript
      - name: Linting Typescript
        run: npm run lint:ts

      # проверяем корректность CSS
      - name: Linting CSS
        run: npm run lint:scss

      # запускаем unit тестирование
      - name: Unit testing
        run: npm run test:unit
